export const OTP_LENGTH = 6
export const RIDE_OTP_LENGTH = 4
export const OTP_TTL_SECONDS = 300
export const OTP_MAX_ATTEMPTS = 10
export const OTP_LOCK_DURATION_MINUTES = 5
export const OTP_RATE_LIMIT_WINDOW_MINUTES = 5
export const OTP_RATE_LIMIT_MAX_REQUESTS = 10

export const JWT_ACCESS_EXPIRY = '15m'
export const JWT_REFRESH_EXPIRY_USER = '30d'
export const JWT_REFRESH_EXPIRY_ADMIN = '24h'
export const REFRESH_TOKEN_BYTES = 32
export const BCRYPT_ROUNDS = 12

export const BROADCAST_WINDOW_SECONDS = 20
export const BROADCAST_MAX_DRIVERS = 5
export const BROADCAST_ROUND_MAX = 3

export const GPS_FLUSH_INTERVAL_SECONDS = 30
export const GPS_ACCURACY_THRESHOLD_METRES = 50
export const SPEED_LIMIT_CITY_KMPH = 50
export const SPEED_LIMIT_HIGHWAY_KMPH = 70

export const DRIVER_MIN_WALLET_BALANCE = 500
export const CASHBACK_RIDE_PERCENT = 0.05
export const CASHBACK_EXPIRY_DAYS = 30
export const REFERRAL_REFERRER_BONUS = 100
export const REFERRAL_REFEREE_BONUS = 50
export const REFERRAL_UNLOCK_AFTER_RIDES = 1

export const GEOCODE_CACHE_TTL_DAYS = 90
export const MAX_STOPS_PER_RIDE = 5
export const ADVANCE_BOOKING_DISPATCH_BUFFER_MINUTES = 15
export const RETURN_CAB_MATCH_RADIUS_METRES = 2000

export const PAGINATION_DEFAULT_LIMIT = 20
export const PAGINATION_MAX_LIMIT = 100
