const { withAppBuildGradle } = require('expo/config-plugins');

// @googlemaps/react-native-navigation-sdk's Android setup requires core library
// desugaring enabled unconditionally (README.md "Enable Core Library Desugaring")
// -- android/ is gitignored and regenerated by `expo prebuild`, so this has to be
// a config plugin, not a one-off manual edit to the generated build.gradle.
module.exports = function withNavigationSdkAndroid(config) {
  return withAppBuildGradle(config, (config) => {
    const contents = config.modResults.contents;

    if (!contents.includes('coreLibraryDesugaringEnabled')) {
      const updated = config.modResults.contents;
      if (/compileOptions\s*\{/.test(updated)) {
        config.modResults.contents = updated.replace(
          /compileOptions\s*\{/,
          `compileOptions {\n        coreLibraryDesugaringEnabled true`
        );
      } else {
        // No compileOptions block exists in the generated build.gradle by default --
        // add one right after `android {` rather than assuming it's already there.
        config.modResults.contents = updated.replace(
          /^android\s*\{/m,
          `android {\n    compileOptions {\n        coreLibraryDesugaringEnabled true\n    }`
        );
      }
    }

    if (!contents.includes('desugar_jdk_libs_nio')) {
      config.modResults.contents = config.modResults.contents.replace(
        /dependencies\s*\{/,
        `dependencies {\n    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs_nio:2.0.4'`
      );
    }

    // com.google.android.libraries.navigation:navigation:7.6.1 (bundled inside
    // @googlemaps/react-native-navigation-sdk) embeds its own compiled copy of
    // com.google.android.gms.maps.model.* classes, which collides with the
    // separate play-services-maps artifact react-native-maps depends on
    // (D8/R8 "Duplicate class" error) -- excluding the standalone play-services-maps
    // artifact here leaves navigation-7.6.1's bundled copy as the sole implementation.
    // NEEDS REAL-DEVICE VERIFICATION of both ActiveRideMap.tsx (react-native-maps)
    // and GoogleGuidedMap.tsx -- compiling clean doesn't prove identical runtime
    // behavior between play-services-maps 19.1.0 and whatever's bundled in 7.6.1.
    if (!config.modResults.contents.includes("module: 'play-services-maps'")) {
      // Top-level block, a sibling of `android { }` -- not valid nested inside it.
      config.modResults.contents =
        `configurations.all {\n    exclude group: 'com.google.android.gms', module: 'play-services-maps'\n}\n\n` +
        config.modResults.contents;
    }

    return config;
  });
};
